# Generated by Django 5.2 on 2025-05-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quickapp', '0004_alter_blog_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
